
def Animate(Current: float, Target: float, Speed: float, AO: float) -> float:
	...

def AnimateSpdUp(Negative: bool, Current: float, Start: float, Target: float, Speed: float, AO: float) -> float:
	...

def FineAnimate(Current: float, Target: float, Speed: float, AO: float, Threshold: float) -> float:
	...

def FineAnimateSpdUp(Negative: bool, Current: float, Start: float, Target: float, Speed: float, AO: float) -> float:
	...

def SmoothEasedAnimate(Current: float, Target: float, Speed: float, AO: float) -> float:
	...